on: [push, pull_request]

env:
  PYTHON_MINIMUM_VERSION: "3.12"

jobs:
  build_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge
      - name: Install dependencies
        run: |
          conda env update --file requirements.txt --name test
          conda list
      - name: Build
        run: mkdir build && cd build && cmake .. && make
      - name: Run tests
        run: ./build/tests/test_make_models